#!/usr/bin/env python3
"""Generate compact 28x40 uppercase reference rasters for the local recognizer."""

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "ui_handwriting_templates.h"
WIDTH = 28
HEIGHT = 40
FONTS = (
    Path(r"C:\Windows\Fonts\segoepr.ttf"),
    Path(r"C:\Windows\Fonts\comic.ttf"),
    Path(r"C:\Windows\Fonts\arial.ttf"),
    Path(r"C:\Windows\Fonts\seguisb.ttf"),
)


def rasterize(font_path: Path, character: str) -> list[int]:
    font = ImageFont.truetype(str(font_path), 72)
    source = Image.new("L", (112, 112), 0)
    draw = ImageDraw.Draw(source)
    draw.text((6, -4), character, font=font, fill=255)
    bounds = source.getbbox()
    if bounds is None:
        raise RuntimeError(f"empty glyph {character} in {font_path}")
    glyph = source.crop(bounds).resize((WIDTH - 3, HEIGHT - 3), Image.Resampling.LANCZOS)
    glyph = glyph.point(lambda value: 255 if value >= 96 else 0)
    canvas = Image.new("1", (WIDTH, HEIGHT), 0)
    canvas.paste(glyph.convert("1"), (1, 1))
    rows: list[int] = []
    for y in range(HEIGHT):
        bits = 0
        for x in range(WIDTH):
            if canvas.getpixel((x, y)):
                bits |= 1 << x
        rows.append(bits)
    return rows


def main() -> None:
    missing = [str(path) for path in FONTS if not path.is_file()]
    if missing:
        raise SystemExit("missing source fonts: " + ", ".join(missing))

    lines = [
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "// Generated by tools/generate-handwriting-templates.py.",
        "// Four complementary print/handwriting faces reduce dependence on one 5x7 shape.",
        f"constexpr uint8_t kHandwritingTemplateVariantCount = {len(FONTS)};",
        "constexpr uint32_t kHandwritingTemplates",
        f"    [kHandwritingTemplateVariantCount][26][{HEIGHT}] = {{",
    ]
    for font_path in FONTS:
        lines.append(f"    {{ // {font_path.name}")
        for character in "ABCDEFGHIJKLMNOPQRSTUVWXYZ":
            rows = rasterize(font_path, character)
            encoded = ", ".join(f"0x{row:07x}u" for row in rows)
            lines.append(f"        {{{encoded}}}, // {character}")
        lines.append("    },")
    lines.extend(("};", ""))
    OUTPUT.write_text("\n".join(lines), encoding="ascii", newline="\n")
    print(f"generated {OUTPUT} ({OUTPUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
